Add SauceLabs Functional Page Loading
merchantprotocol/PHP-Sausage-Selenium pull request #2
Opened 2017-01-27 20:02 UTC by alex-nov-git

Added: 4 independent tests in one class, that provide tests for
admin, order, frontend and customers pages. Each test checks
all pages of its type, and then checks if one or more pages crach.
TODO: remove creating customer from all tests and move it to the Fixture.

2017-01-27 20:14 UTC, d10nZ requested changes

2017-01-27 20:14 UTC, d10nZ commented on tests/Magento_Page_Loading.php
> +    const ADMIN_USERNAME    = 'denis';
please replace it with **user** which will be used only for **test** purposes
such functionality should be moved into separate config.php file

2017-01-27 20:23 UTC, jonathonbyrdziak requested changes

2017-01-27 20:23 UTC, Jonathonbyrd commented on tests/Magento_Page_Loading.php
> +            'link' => '/doneright/enhanced/dashboard',
The admin url prefix `doneright` should be moved into a separate config file

2017-01-27 20:23 UTC, Jonathonbyrd commented on tests/Magento_Page_Loading.php
> +    ];
separate config file for the list of pages to test

2017-01-27 20:23 UTC, Jonathonbyrd commented on tests/Magento_Page_Loading.php
> +        }
should be "Admin links *not* found"

2017-01-27 20:23 UTC, Jonathonbyrd commented
Looking good so far.

2017-01-27 21:01 UTC, d10nZ commented on tests/Magento_Page_Loading.php
> +            'link' => '/doneright/enhanced/dashboard',
moreover we should move into separate config file all specific data and parameters which can be used by all of us (config.local.php) and by travis CI service (config.staging.php)

domain name => ''
admin domain name => ''
preferred browsers => []
admin_account => [login => 'test', pass=> 'test']
customer_account => [login => 'test', pass=> 'test']
etc

2017-01-27 21:04 UTC, d10nZ commented on tests/Magento_Page_Loading.php
> +    ];
it is better to use dataProvider
see: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html
   chanpter: 'Data Providers'

2017-01-27 22:08 UTC, alex-nov-git commented on tests/Magento_Page_Loading.php
> +     * Testing of pages loading in customer account
Fix comment

2017-01-29 10:56 UTC, ghost commented on Makefile
> +    vendor/bin/paratest -p 4 -f --verbose --phpunit=vendor/bin/phpunit tests/Magento_Page_Loading.php
I think that is better use 'tab' instead 'spaces'.

```
Tab Makefile
In order for make to tell the difference between a recipe and things that are not a recipe, it uses TAB characters. So, lines that begin with TAB are assumed to be part of a recipe (so they are shell scripts and passed to the shell for parsing), and lines that do not begin with TAB cannot be part of a recipe (so they cannot be shell scripts: they must be make syntax).
```

2017-02-01 14:47 UTC, d10nZ approved these changes

2017-02-01 14:54 UTC, alex-nov-git commented on tests/Magento_Page_Loading.php
> +            'link' => '/doneright/enhanced/dashboard',
I moved these links into separate configuration file. We can use this file as a global configuration for testing module. But at the same time these links may seem irrelevant in the global configuration file. The data provider method is simple method to provide arguments for test method, so we should understand that the data provider and separate links in config file is a different things. We can use links from separate config file or data provider, that returns array with hard coded links for this test case, or data provider, that returns array with links from configuration, what do you say?

2017-02-01 16:19 UTC, jonathonbyrdziak approved these changes

2017-02-02 09:06 UTC, merged